#!/usr/bin/env bun
// tools/media/register.mjs
// Build trunk/media/registry.yaml from tools/mirror-shopify-images.map +
// per-scope _manifest.tsv files in _media-source/shopify-mirror/<scope>/.
//
// Spec: trunk/schema/media.schema.json (CW-003: lokale Originale pflichtig).
//
// Usage:
//   bun tools/media/register.mjs [--write]
//
// Without --write: dry-run, prints YAML to stdout.
// With --write: replaces trunk/media/registry.yaml.
//
// Each map line (scope<TAB>local_name<TAB>source_url) becomes one registry
// entry keyed by the basename without extension. backup_local points to
// _media-source/shopify-mirror/<scope>/<local_name>; uploaded date is taken
// from the file's mtime (rounded to date).

import { readFileSync, writeFileSync, statSync, existsSync } from "node:fs";
import { resolve, dirname, basename, extname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";
import { tenantPath, tenantIsExamples, tenantDescribe } from "../lib/tenant-path.mjs";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const MAP = resolve(REPO_ROOT, "tools/mirror-shopify-images.map");
const DEFAULT_REG = tenantIsExamples()
  ? resolve(REPO_ROOT, "trunk/media/registry.yaml")
  : tenantPath("trunk/media/registry.yaml");
const REG = process.env.MEDIA_REGISTRY_PATH
  ? resolve(process.env.MEDIA_REGISTRY_PATH)
  : DEFAULT_REG;
const MIRROR = resolve(REPO_ROOT, "_media-source/shopify-mirror");

const write = process.argv.includes("--write");

function die(msg) {
  process.stderr.write(`register: ${msg}\n`);
  process.exit(1);
}

if (!existsSync(MAP)) die(`map missing: ${MAP}`);

const lines = readFileSync(MAP, "utf8").split("\n");
const entries = {};

for (const raw of lines) {
  const line = raw.trim();
  if (!line || line.startsWith("#")) continue;
  const [scope, localName, url] = raw.split("\t");
  if (!scope || !localName || !url) continue;

  const localPath = resolve(MIRROR, scope, localName);
  if (!existsSync(localPath)) {
    process.stderr.write(`register: WARN missing local file ${relative(REPO_ROOT, localPath)}\n`);
    continue;
  }

  const key = basename(localName, extname(localName));
  if (entries[key]) {
    process.stderr.write(`register: WARN duplicate key ${key} (overwriting)\n`);
  }

  const mtime = statSync(localPath).mtime;
  const isoDate = mtime.toISOString().slice(0, 10);

  entries[key] = {
    master_backend: "shopify_files",
    master_url: url.trim(),
    backup_local: relative(REPO_ROOT, localPath),
    uploaded: isoDate,
    rechte: "© Sanexio GmbH",
    alt: { de: humanize(key) },
    sites: { juvantis: "auto-synced", praxis: "auto-synced" }
  };
}

function humanize(slug) {
  return slug
    .replace(/^(diag-|labor-|leist-|detail-)/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (m) => m.toUpperCase());
}

const header = `# Cortex-Web Media-Registry — auto-generated by tools/media/register.mjs
# Schema: trunk/schema/media.schema.json
# Re-build: bun tools/media/register.mjs --write
# Quelle: tools/mirror-shopify-images.map + _media-source/shopify-mirror/*/_manifest.tsv
# CW-003: jedes shopify_files-Asset hat lokale Kopie (backup_local).
`;

const out = header + yaml.dump(entries, { lineWidth: 0, sortKeys: true });

if (write) {
  writeFileSync(REG, out);
  process.stderr.write(`register: ${tenantDescribe()}\n`);
  process.stderr.write(`register: wrote ${Object.keys(entries).length} entries to ${relative(REPO_ROOT, REG)}\n`);
} else {
  process.stdout.write(out);
  process.stderr.write(`register: ${tenantDescribe()}\n`);
  process.stderr.write(`register: dry-run (${Object.keys(entries).length} entries) — pass --write to persist\n`);
}
