// Cortex-Web Astro-Adapter — File-Output-Helper.
// Schreibt TypeScript-Data-Files in <tenant.astro.repo_path>/src/data/
// und Astro-Page-Files in src/pages/. Vor jedem Überschreiben wird ein
// Backup nach adapters/astro/.backups/ angelegt (CW-008-Backup-Pflicht).
//
// Der Ziel-Repo-Pfad wird per `tenant.config.json` → `astro.repo_path`
// aufgelöst (relativ zum Cortex-Web-Framework-Root). Vor Welle 15 war
// `sites/sanexio-github-io/repo` hartcodiert.

import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from "node:fs";
import { dirname, resolve, basename } from "node:path";
import { tenantConfigGet } from "../../../tools/lib/tenant-config.mjs";

const REPO_ROOT = resolve(import.meta.dir, "../../..");
const BACKUP_DIR = resolve(REPO_ROOT, "adapters/astro/.backups");

let _astroRepoCache = null;

function astroRepoRoot() {
  if (_astroRepoCache) return _astroRepoCache;
  const rel = tenantConfigGet("astro.repo_path");
  _astroRepoCache = resolve(REPO_ROOT, rel);
  return _astroRepoCache;
}

export function astroPath(rel) {
  return resolve(astroRepoRoot(), rel);
}

function timestampIso() {
  return new Date().toISOString().replace(/[:.]/g, "-");
}

function ensureDir(dir) {
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

/**
 * Backup-the-existing-file-then-write contract.
 * Throws if backup fails — never silently overwrites.
 */
export function writeWithBackup(targetAbsPath, contents) {
  ensureDir(dirname(targetAbsPath));

  if (existsSync(targetAbsPath)) {
    ensureDir(BACKUP_DIR);
    const backupName = `${timestampIso()}_${basename(targetAbsPath)}.bak`;
    const backupPath = resolve(BACKUP_DIR, backupName);
    try {
      copyFileSync(targetAbsPath, backupPath);
    } catch (err) {
      throw new Error(`Backup failed (${err.message}) — refusing to overwrite ${targetAbsPath}`);
    }
  }

  writeFileSync(targetAbsPath, contents, "utf8");
}

/**
 * Auto-Generated-Header for TS output files. Editing the file by hand
 * is technically possible but will be overwritten by the next adapter run.
 */
export function tsHeader(sourceList) {
  const lines = [
    "// ============================================================",
    "// AUTO-GENERATED by Cortex-Web Astro-Adapter — DO NOT EDIT.",
    "// ",
    "// Source-of-truth: ~/Cortex/projects/Cortex-Web/trunk/",
    "// Regenerate with: bun adapters/astro/build.mjs",
    "// ",
    "// Source files:",
  ];
  for (const s of sourceList) lines.push(`//   - ${s}`);
  lines.push(`// Generated: ${new Date().toISOString()}`);
  lines.push("// ============================================================");
  lines.push("");
  return lines.join("\n");
}

/**
 * Serialize a JS object as a TS export const. Minimal — covers plain
 * JSON-safe values (string, number, boolean, null, arrays, objects).
 */
export function tsExportConst(name, value, typeAnnotation = "") {
  const body = JSON.stringify(value, null, 2);
  const ann = typeAnnotation ? `: ${typeAnnotation}` : "";
  return `export const ${name}${ann} = ${body} as const;\n`;
}
